apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-exchange-api-sa
  namespace: file-exchange
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::976837153996:role/poc-file-exchange-eks-role